### ISSUE TITLE
Integration of Krypton-OutlookGrid into toolkit

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-NET-4.70#19]
I have requested permission of @Cocotteseb to incorporate their project [Krypton-OutlookGrid
](https://github.com/Cocotteseb/Krypton-OutlookGrid) into this toolkit for .NET versions 4.6.2, 4.7 & 4.71. Awaiting response.

**Comment by Wagnerp** [comment]
Merged with extended toolkit

**Comment by Cocotteseb** [comment]
Sorry for not answering before. 
I'm OK with the integration (it is under MS-PL license). A link to the original project would be great!

If you modify/add features it could be great to synchronize and vice-versa. (I think on github it does work with pull request right ?)

**Comment by Wagnerp** [comment]
Hi @Cocotteseb,

Many thanks for replying, I'm going to integrate it into the extended toolkit project. While that project is on a GPL 3.0 license, I have kept the original MS-PL license for the Krypton Outlook grid portion of it. If you wish to follow/contribute towards it, please see [Krypton-Toolkit-Suite-Extended-NET-4.7](https://github.com/Wagnerp/Krypton-Toolkit-Suite-Extended-NET-4.7).
