### ISSUE TITLE
Building for 64-bit

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-NET-4.70#28]
See: https://blogs.msdn.microsoft.com/tolong/2007/03/20/use-visual-studio-to-build-64-bit-application/ and https://msdn.microsoft.com/en-us/library/ms185328.aspx

**Comment by Smurf-IV** [comment]
Why?
`ANY CPU` allows the hosting process to determine the "Bitness", just set `Prefer 32Bit` to false in the project properties - to allow the compiler to hint for x64 in the AnyCPU JIT

**Comment by Wagnerp** [comment]
So if anyone needs just the x32 or x64 versions they are there. The 'Fat Binary' `Any CPU` version is still in the `source` folder, and will not be removed. On another note, I'm just completing the UAC shield controls in the extended toolkit. Will upload code shortly.

**Comment by Smurf-IV** [comment]
Ermm.. Not sure "Fat binary" is right.. 
Build 524 zip = 1.92MB, Latest x64 also = 1.92MB.
Am I missing something ?

**Comment by Wagnerp** [comment]
Does a `Any CPU` dll or executable change it's architecture depending on the CPU, as I always thought that it was always 32-bit only? On another note, I have successfully got the UAC prompt working for certain controls in the Extended Toolkit. I need to fix the `KryptonCueTextBox` and the `KryptonMostRecentlyUsedFileMenuItem`.

**Comment by Smurf-IV** [comment]
> Does a Any CPU dll or executable change it's architecture depending on the CPU
Yes and No.
I'll try to explain "My understanding" of this.
DLL's should be "Any CPU", as this allows the hosting process to determine the bitness they will be running in. Then the JIT does it job as required.
For Exe's it is a bit more complicated. In the Project properties there is an option to set the "Preferred" target bitness, if the current build is "Any CPU", then there are the direct options of x86, and x64 (Ignoring the old Intel mess). 
So if the exe is "Any" and the Preferred is not "32 bit" (Yes I know they made a mess of the name), then .Net CLR will attempt to go into x64 first, and then drop x86 afterwards, all before the actual "Main" is loaded.

So, As these projects are not relying on thirdparty dll's which have been locked to x64 (Or x86 like HW ones do) then leave them as x64. However, the Test apps can be whatever you want to allow trials (Especially if you want to test large memory things like images etc.)

HTH

**Comment by Wagnerp** [comment]
Thanks for the explanation, you can ignore the x86 and x64 if you want. I have altered how each solution builds though, so they have named folders, instead of having one big mess of an output directory.
