### ISSUE TITLE
Renaming of DLLs Assembly Name Suggestion

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-NET-4.70#43]
Just a thought, should we rename the relevant DLL assembly names i.e `ComponentFactory.Krypton.Design.dll` to `Krypton Design.dll` etc, but keep the namespace names 'as is' for obvious reasons?

**Comment by Smurf-IV** [comment]
I think "we" would be allowed to, but then it would be more of a derivative work, (Which it is) and "we" still keep the original header "mostly" intact as requested by the original license, so Yeah, go ahead.
Whilst at it, Can you also get rid of all the architecture stuff, or are you still convinced it makes a difference ?

**Comment by Smurf-IV** [comment]
Company name could be the github address !

**Comment by Wagnerp** [comment]
A new installer has just been released. It supports Windows 7 and higher. I personally don't think both XP and Vista should be supported, as they're old systems and don't support .NET 4.7. As for the updater, if that fails, then I do have a backup plan, which I'll work on this week.

**Comment by Wagnerp** [comment]
I'm putting in a folder called `Failsafe` with the original DLL filenames still in tact, just in case something goes haywire.
