### ISSUE TITLE
Is there any good web editing add-ons for VS?

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-NET-4.70#46]
Are there any good web editing add-ons for VS, as I'm going to create a HTML based changelog for the updater utility. Got a good table design in mind.

**Comment by Smurf-IV** [comment]
Use the split screen already built into VS..

You have to enable it via the "Open With" for HTML pages initially (Search howto via google) but it's great for direct editing,
Or "More controversially" use MS WORD

**Comment by Wagnerp** [comment]
I have got a version of MS Expression 4. Maybe I need to boot up the old Win 7 VM.
