### ISSUE TITLE
All Controls are placed Bottom of Form

### ISSUE THREAD

**Issue by pc8181** [Wagnerp/Krypton-NET-4.70#48]
Hi,
   Today (2018/May/05) installed VS 2017 with Krypton-Net-4.70 but it does not come withVS-toolbox so I added manually after that I try to add button and any other controls in form but they are placed into bottom of form like component I could not add any controls directly to form please help …..

**Comment by Wagnerp** [comment]
Hi,

There is a bug within the designer, as a temporary measure, I would recommend that you use the DLLs contained in the `Failsafe` folder until this bug is ironed out.

**Comment by pc8181** [comment]
thanks for the reply, where is the `Failsafe `folder ?, please help

**Comment by Wagnerp** [comment]
I'll upload a `zip` file containing these files shortly.

**Comment by Wagnerp** [comment]
Update: It's uploaded.

**Comment by pc8181** [comment]
thanks for the great help ... but it does not resolve this problem i added filesafe dll's but the same problem persists and also i tried to compile myself and tried, same problem .... please help

![image](https://user-images.githubusercontent.com/13380400/39665901-1cd9e6f2-5050-11e8-9a04-7dfa59b0cf12.png)

**Comment by Wagnerp** [comment]
It's because you need to add the reference `ComponentFactory.Krypton.Design.dll` to your project before you can use the controls.

**Comment by pc8181** [comment]
yes, after i did it, working fine ... thanx

**Comment by Wagnerp** [comment]
I'm glad that it's working for you now.
