### ISSUE TITLE
Status Strip Labels

### ISSUE THREAD

**Issue by fdncred** [Wagnerp/Krypton-NET-4.70#52]
Is there a way to make changes to the status strip labels individually, such as changing foreground, background, and font?

Once I set the status strip to ManagerRenderMode all that type of styling goes away.

Thanks,
Darren

**Comment by Wagnerp** [comment]
Hi, I would reccomend that you have a look at the `Palette Designer` if you want to create your own custom theme.

**Comment by fdncred** [comment]
I have looked at Palette Designer and all the rest of the examples and source code. Nothing appears to indicate that one can control and individual status item's foreground or background color. You can change them all via the Palette, but none of them individually. That is what I'm questioning.

**Comment by Wagnerp** [comment]
You can change the font, also there is a way that you can have two colours, but I think these options are buried deep within the properties. In my 'Extended Toolkit', we may make it so that these options are easier to find.

**Comment by fdncred** [comment]
Would you mind pointing out to me where it exists in the extended toolkit please? I'm looking and don't see it.

**Comment by Wagnerp** [comment]
It's not started development yet, but if you want to change the properties, all values will be under the `StateCommon` tree of each control.

**Comment by Wagnerp** [comment]
I have now uploaded 26 new themes, one of which is a clone of Access red. You can request a theme, have a look at readme for more details.

![access red](https://user-images.githubusercontent.com/949607/40466841-4d0ec850-5f1f-11e8-9279-66962040d0cf.PNG)

**Comment by fdncred** [comment]
I guess I need more verbosity. Where are these new themes? I looked through the commits and didn't see them. Themes are great but if I can't control individual status strip items foreground/background color then it doesn't really address the issue for me.

**Comment by Wagnerp** [comment]
They are in the `Palettes` folder, there are 52 new themes in total. If you need just the status strip need themeing please let me know, and I can craft one for you. I'll need details of the foreground/background colours, plus the choice of Office 2007/2010 or 2013 design.

**Comment by fdncred** [comment]
Can you help me understand what I'm doing wrong with this code? I'm trying to test out all the palettes but when you change them, one after the other, some artifacts are left behind and the full palette isn't drawn completely.

[kPaletteForm.zip](https://github.com/Wagnerp/Krypton-NET-4.70/files/2058854/kPaletteForm.zip)

Start out like this.
![kpaletteform-start](https://user-images.githubusercontent.com/343840/40791975-5ae82760-64be-11e8-80a7-4882c257688d.png)

Later it looks like this with artifacts with several of the palettes.
![kpaletteform-blue-alt](https://user-images.githubusercontent.com/343840/40792019-7b6bac50-64be-11e8-8251-2f1e66b413c0.png)


As a side note, I don't see how changing a palette address what I'm trying to do which is change the color of each individual status strip items dynamically. So, if something is bad, make the background red for that one item. If something is good, make the background for that one item green.

I guess theoretically I could have a palette for each condition and load it  upon the bad or good event but then I'd have dozens and dozens of palettes to accommodate every possible condition. So that isn't really an option.

**Comment by Wagnerp** [comment]
Yes, I think it's a colour region that I missed out thanks for pointing it out. It is possible to create two palettes for the statusstrip, but you may need more than one `KryptonManager` to switch between.

**Comment by Wagnerp** [comment]
This is how it should look:

![capture](https://user-images.githubusercontent.com/949607/40797042-c7dd9fb8-64fe-11e8-82eb-c80dbccb62a5.jpg)

**Comment by Wagnerp** [comment]
Created some palettes that you may be looking for

[ProofOfConcept.zip](https://github.com/Wagnerp/Krypton-NET-4.70/files/2059384/ProofOfConcept.zip)

**Comment by Wagnerp** [comment]
I see what you're looking for now. No the current toolkit doesn't support this, but if you would like to request this feature, then by all means please submit the request on the `Extended Toolkit` repo. Thanks!
