### ISSUE TITLE
Is there a larger version of the logo?

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-NET-4.70#62]
It's for use for a rewrite of the `Krypton Explorer`

**Comment by Wagnerp** [comment]
Thanks, I'm redoing it to minimise repetitive code. It will look similar to  the old UI, with major changes to the code.

**Comment by Wagnerp** [comment]
Edit: I may try to recreate it in photoshop, and upload a raw `*.psd` file of 512 x 512. This will allow us to create a new 'Kr' `*.ico` file, which will replace the old puzzle icon. It will also allow us to add layers/textures etc as we see fit. PSD files can be imported into Paint .NET.

**Comment by Smurf-IV** [comment]
Cool
Some ideas:
https://wallpapercave.com/periodic-table-wallpaper
http://periodictableimage.com/wp-content/uploads/2018/04/Periodic-Table-Hd-Wallpaper-1920x1080.jpg

**Comment by Wagnerp** [comment]
What's your thought of a hexagonal shape for each letter? http://periodictableimage.com/wp-content/uploads/2018/06/Periodic-Table-Hd-Images-Wallpapers.jpg

**Comment by Wagnerp** [comment]
@Smurf-IV 

Before I go ahead and make the rest of the letters, what's your thought on this design?

![kr hexagon](https://user-images.githubusercontent.com/949607/43048332-d17c3068-8ddd-11e8-972d-5ab81a80ba1c.png)

I could always use the blue palette colour?

**Comment by Wagnerp** [comment]
![kr hexagon office 2010 blue](https://user-images.githubusercontent.com/949607/43048471-e1d5825a-8ddf-11e8-83f9-032254025f8e.png)

**Comment by Smurf-IV** [comment]
- When the Hexagons are compressed to make a 32*32 icon the text will probably be unreadable, and the Kr will be lost to just a a blob that "might" look like a K.
That's why I chose the square shape..
- Blue would fit in with the existing theme, but I wanted to move it away from the existing one to try and show that the new Krypton is "different"..
Your Choice :-)

**Comment by Wagnerp** [comment]
Yes, sure. I'm playing about with different fonts also.

![transparent kr hexagon office 2010 blue test text 512 x 512](https://user-images.githubusercontent.com/949607/43063339-6c3b8d72-8e53-11e8-8054-441abb600f1a.png)

Could try green and a circular design?

**Comment by Wagnerp** [comment]
![square design 512 x 512 green](https://user-images.githubusercontent.com/949607/43064915-2a41894e-8e58-11e8-89cc-594ca95475eb.png)

This one may actually work

**Comment by Smurf-IV** [comment]
center font need to be bold, in order for it not to be lost when the pixels
are reduced.

**Comment by Wagnerp** [comment]
Do you mean like this?

![square design 512 x 512 green](https://user-images.githubusercontent.com/949607/43305355-6015f9aa-916f-11e8-89bd-cf094f201b4c.png)

**Comment by Smurf-IV** [comment]
Maybe more. Try reduce to a 24 pixel square (16 used to the minimum but I have not come across a sensible display of that since Win XP went out of fashion!)

**Comment by Wagnerp** [comment]
This is the icon at 24 x 24 pixels:

![square design 24 x 24 green](https://user-images.githubusercontent.com/949607/44338526-06ae9100-a476-11e8-8c2a-a35ae1390d3a.png)

**Comment by Smurf-IV** [comment]
That ico file is not valid according to windows :-(
The reason it is blurry is down to re-sampling, you'll have to sharpen as well. That will forcefully lose some information, but make it clearer for the crucial part, which is the **Kr**

**Comment by Wagnerp** [comment]
That's odd, as I used paint .net to create the ico file. I'll have a look tomorrow. In other news, I've successfully created a new palette creator (not all features are functional at the moment), but would you mind testing it when you have some spare time? I've also started development on a new customisable message box.
