### ISSUE TITLE
Ctrl+c to copy

### ISSUE THREAD

**Issue by herledant** [Wagnerp/Krypton-NET-4.70#67]
Hello,

is it a way to deactivate this functionnality on kryptonmessagebox and kryptontaskdialog?

Best Regard's

**Comment by Smurf-IV** [comment]
I think it only displays when the Type of Icon is Error, so don't use that for Messages / info/ warning etc.

**Comment by herledant** [comment]
Hello Smurf-IV,

In fact it display with warning and error message on kryptonmessagebox and always on kryptontaskdialog.
Is it a way to never display it? I don't need it and i prefer hide this option.

**Comment by Smurf-IV** [comment]
@herledant I have added a design time property to the TaskDialog
```
        /// <summary>
        /// Allows user to override the default "Ctrl+c to copy" in window caption
        /// </summary>
        [Category("Appearance")]
        [Description("'ExtraText' in Caption of the window.")]
        [DefaultValue("")]
        [Localizable(true)]
        [Bindable(true)]
        public string TextExtra
```

And an optional nullable bool for each of the messageBox API's 
```
/// <param name="showCtrlCopy">Show extraText in title. If null(default) then only when Warning or Error icon is used.</param>
bool? showCtrlCopy=null
```

**Comment by herledant** [comment]
Hello Smurf-IV
Thank's a lot to have made the modification.
For Kryptonmessagebox, it's clear how to disable the "ctrl+c" option.

For KryptonTaskDialog i'm not sure to have well understand how to disable this option.
Is this just by setting the textextra parameter to nothing?

One more question about the Kryptonmessagebox control:
What is IWin32Window showOwner parameter?
I don't understant for what it is.

**Comment by Smurf-IV** [comment]
> For KryptonTaskDialog i'm not sure to have well understand how to disable this option.
> Is this just by setting the textextra parameter to nothing?

Correct (`string.Empty`)
> 
> One more question about the Kryptonmessagebox control:
> What is IWin32Window showOwner parameter?

The same description as in the MSDN for MessageBox. 
> I don't understant for what it is.

It allows the messagebox to be set to a certain control / Form, rather than just a default null, which then the codes attempts to seek out an owner

**Comment by Wagnerp** [comment]
Or you you could just put `TextExtra = "";`

**Comment by herledant** [comment]
OK many thank's for your answer!
Great job!
