### ISSUE TITLE
The look of krypton themes does not appear in windows 10 when I use the ribbon control

### ISSUE THREAD

**Issue by GeraldoJansen** [Wagnerp/Krypton-NET-4.70#68]
I'm developing a project and wanted to use the visual krypton and its controls, but I need my project to have the .NET 4.5 version so I managed the dll's to 4.5. I can not use the Ribbon and the Krypton look of the form together. When I use the two together the form gets a glitch in the visual and windows 10 continues as the visual for the form. I need help with this bug. @Wagnerp @saleyn @Smurf-IV

**Comment by GeraldoJansen** [comment]
I put "kryptonRibbon1.AllowFormIntegrate = false;" and the form appeared the visual. Anyway, thank you very much for your work.

**Comment by GeraldoJansen** [comment]
I'm a big fan of your work. Thank you for the initiative, that is of great importance to me and to many others. @Wagnerp

**Comment by Smurf-IV** [comment]
I have found the workaround. I'll do a fix for it soon..
Workaround:
In the Form, 
After `InitializeComponent();`
you have to "**Force**" `kryptonRibbon1.AllowFormIntegrate = false;`
