### ISSUE TITLE
KryptonForm to have a DropShadow designer boolean

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-4.70#9]
Thoughts on extending `KryptonForm `to have an option (default to true) for displaying drop shadow ? 

Implementing code from https://github.com/Cocotteseb/Krypton/issues/1
via a designer attribute.

**Comment by Wagnerp** [comment]
Yes sure, as the original toolkit was designed for Vista & 7. A while ago, I was thinking about creating a Visual Studio extension to allow users to create a new KryptonForm via the new item dialog box, what are your thoughts on it? With the proposed code, would that be a bool value?

**Comment by Wagnerp** [comment]
Sorry I can't merge your latest commit, please see my comment I've posted on the thread. My fault :(

**Comment by Smurf-IV** [comment]
The bool will state if DropShadow is on via the designer properties
e.g. `Use DropShadow | true`

**Comment by Wagnerp** [comment]
Ok, I've uploaded some new code. It may not be efficient, but I've included a new property called 'UseDropShadow' with a default value of true, along with a new method called 'UpdateDropShadowDraw()' which accepts a bool value in a new region labelled 'Drop Shadow Methods'.

**Comment by Smurf-IV** [comment]
FYI:
When opening an existing project, the default value of `UseDropShadow `is `False`
Setting it to `True`, does not enable the drop shadow ? 
This is in a "Child Form" and not the Main form.

**Comment by Wagnerp** [comment]
The code is in the 'KryptonForm' class I thought that I had set the default value of the property to true. Might also be an incorrect signature type for  'UpdateDropShadowDraw()'. Might need to be CreateParams instead of void.

**Comment by Wagnerp** [comment]
As a note, I have reached out to @Cocotteseb about the screen clipping issue, as I can't find the _drawIndicator variable that they used.

**Comment by Smurf-IV** [comment]
Still not working by default (i.e. no variable set) . Picture shows Parent underneath set by explicit code, Child form over the top that supposed to Auto set but is showing it is not.
![image](https://user-images.githubusercontent.com/2418812/34920860-99218dd6-f971-11e7-9eda-409d972bc210.png)
This is from your latest code set.

**Comment by Wagnerp** [comment]
Where would the child form code come from I wonder? If I know that, then it should be a quick fix! Does it work on the parent form?

**Comment by Smurf-IV** [comment]
My Elucidate project https://github.com/Smurf-IV/Elucidate/blob/master/Elucidate/Elucidate/Elucidate.cs
Line 75 then initiates the form via line 109.
My Code does not rely on the Parent "Main" Form doing the work via Krypton, as that is already in the code - (That's what I want to remove it from mine and use code with Krypton.).
In My checked out code -> they are both derived from `KryptonForm`, hence the "Blue look theme" as in the picture above.

**Comment by Smurf-IV** [comment]
In the following code:

![image](https://user-images.githubusercontent.com/2418812/34954255-a89abb1a-fa17-11e7-8507-47235b05501d.png)

What does line 1605 do to the creation parameters ?

**Comment by Wagnerp** [comment]
That's a Q & D call to  the method which deals with the shadow which starts on line 1609. The GetCreateParams method draws the shadow. I should have called the method 'DrawShadow' to make more sense. Will change it after I've merged your pull request. I will take a look at the MdiForm issue tomorrow, thanks for the heads-up.

**Comment by Smurf-IV** [comment]
What I tried to say, is that the `createParams` is a local copy and you then return it from the `DrawShadow` function, **but** nothing uses it. Hence why in my Win 8.1 test environment, where you have to turn on shadows per app, via the app, the code does not work.  Win 10 has "Some" shadowing on by default for all apps.

**Comment by Wagnerp** [comment]
Uhmm.. that's odd, I wonder if it has something to do with it being converted into a method, as the original code was a typical 'getter/setter' code block?

**Comment by Wagnerp** [comment]
I could set the shadow to on by default, though you wouldn't be able to turn it off until I can find a way to make sense. An idea, could the property CreateParams be returned in the DrawShadow method? i.e

`protected override CreateParams CreateParams
        
            get
            {
                // add the drop shadow flag for automatically drawing
                // a drop shadow around the form
                CreateParams cp = base.CreateParams;
                cp.ClassStyle |= CS_DROPSHADOW;
                return cp;
            }
        }`

then

`private CreateParams DrawDropShadow()
        {
            CreateParams cp;

            return cp;
        }`

**Comment by Smurf-IV** [comment]
The Shadow seems to be working by default, BUT in windows 10 it causes the following to happen..

(And for some reason I cannot upload an image)

**Comment by Smurf-IV** [comment]
On Windows 10, With the Professional ###  themes, the Drop Shadow is a solid line (Might not be related to drop shadow, but that is what it looks like)

**Comment by Wagnerp** [comment]
Would it be possible to put a theme check in, i.e.:

if theme == professional then
// DO NOT HAVE DROP SHADOW
